import SwiftUI

public enum WeeklyActivityChartDefaults {
    public static let maxValue: Double = 100
    public static let trendPercentage: Double = 23
    public static let highlightBadgeSpacing: CGFloat = 30
    public static let plotHeight: CGFloat = 350
    public static let minimumPlotHeight: CGFloat = 120
    public static let cardCornerRadius: CGFloat = 22
}

enum WeeklyActivityChartLayout {
    static let animationDuration: Double = 0.9
    static let sampleHighlightedIndex = 5
    static let cardCornerRadius = WeeklyActivityChartDefaults.cardCornerRadius
    static let cardHorizontalPadding: CGFloat = 20
    static let cardTopPadding: CGFloat = 22
    static let cardBottomPadding: CGFloat = 18
    static let cardOuterHorizontalPadding: CGFloat = 34
    static let cardOuterVerticalPadding: CGFloat = 30
    static let cardBorderLineWidth: CGFloat = 2
    static let cardShadowOpacity: Double = 0.32
    static let cardShadowRadius: CGFloat = 26
    static let cardShadowYOffset: CGFloat = 18
    static let mobileHorizontalPadding: CGFloat = 18
    static let mobileVerticalPadding: CGFloat = 24
    static let headerSpacing: CGFloat = 18
    static let headerTitleSize: CGFloat = 28
    static let headerSubtitleSize: CGFloat = 17
    static let headerColumnSpacing: CGFloat = 9
    static let headerTrendSpacing: CGFloat = 12
    static let headerSpacerMinLength: CGFloat = 6
    static let headerTitleMinimumScale: CGFloat = 0.76
    static let plotHeight = WeeklyActivityChartDefaults.plotHeight
    static let compactPlotHeight: CGFloat = 190
    static let compactHeightThreshold: CGFloat = 380
    static let edgeExtensionFactor: CGFloat = 0.82
    static let chartGridStepCount = 4
    static let gridLineWidth: CGFloat = 1
    static let gridDash: [CGFloat] = [6, 8]
    static let axisLineWidth: CGFloat = 1
    static let lineWidth: CGFloat = 5
    static let areaTopInset: CGFloat = 2
    static let areaPrimaryOpacity: Double = 0.78
    static let areaSecondaryOpacity: Double = 0.34
    static let areaPrimaryTopMaskOpacity: Double = 0.92
    static let areaPrimaryMiddleMaskOpacity: Double = 0.46
    static let areaPrimaryBottomMaskOpacity: Double = 0.10
    static let areaSecondaryTopMaskOpacity: Double = 0.88
    static let areaSecondaryMiddleMaskOpacity: Double = 0.10
    static let areaSecondaryBottomMaskOpacity: Double = 0.03
    static let areaMaskTopHoldLocation: Double = 0.18
    static let areaMaskMiddleLocation: Double = 0.48
    static let areaMaskBottomLocation: Double = 0.74
    static let edgeFadeFirstLocation: CGFloat = 0.28
    static let edgeFadeSecondLocation: CGFloat = 0.62
    static let edgeFadeFirstOpacityMultiplier: Double = 0.22
    static let edgeFadeSecondOpacityMultiplier: Double = 0.62
    static let rightFadeFirstLocation: CGFloat = 0.48
    static let rightFadeSecondLocation: CGFloat = 0.72
    static let rightFadeFirstOpacityMultiplier: Double = 0.42
    static let rightFadeSecondOpacityMultiplier: Double = 0.22
    static let markerSize: CGFloat = 12
    static let highlightedMarkerSize: CGFloat = 14
    static let highlightedInnerRingSize: CGFloat = 26
    static let highlightedOuterRingSize: CGFloat = 38
    static let highlightedInnerRingOpacity: Double = 0.8
    static let highlightedOuterRingOpacity: Double = 0.5
    static let highlightedInnerRingWidth: CGFloat = 3
    static let highlightedOuterRingWidth: CGFloat = 1.8
    static let markerStrokeWidth: CGFloat = 2.4
    static let highlightedMarkerStrokeWidth: CGFloat = 3
    static let markerShadowOpacity: Double = 0.78
    static let markerShadowRadius: CGFloat = 5
    static let highlightedMarkerShadowRadius: CGFloat = 9
    static let markerInitialScale: CGFloat = 0.2
    static let pointGlowSize: CGFloat = 42
    static let highlightedPointGlowSize: CGFloat = 68
    static let pointGlowStartOpacity: Double = 0.32
    static let pointGlowMiddleOpacity: Double = 0.18
    static let highlightedPointGlowStartOpacity: Double = 0.24
    static let highlightedPointGlowMiddleOpacity: Double = 0.16
    static let pointGlowBlurRadius: CGFloat = 7
    static let highlightedPointGlowBlurRadius: CGFloat = 10
    static let pointValueFontSize: CGFloat = 14
    static let pointValueYOffset: CGFloat = 22
    static let pointValueOpacity: Double = 0.92
    static let badgeHeight: CGFloat = 50
    static let badgeWidth: CGFloat = 60
    static let badgeCornerRadius: CGFloat = 14
    static let badgeTextSpacing: CGFloat = 2
    static let badgeLabelSize: CGFloat = 13
    static let badgeValueSize: CGFloat = 20
    static let badgeBorderOpacity: Double = 0.58
    static let badgeBorderLineWidth: CGFloat = 1.5
    static let badgeShadowOpacity: Double = 0.32
    static let badgeShadowRadius: CGFloat = 14
    static let markerRadius: CGFloat = 7
    static let badgeEdgeInset: CGFloat = 40
    static let badgeConnectorTopGap: CGFloat = 6
    static let badgeConnectorBottomGap: CGFloat = 5
    static let guideLineWidth: CGFloat = 1.6
    static let guideDash: [CGFloat] = [5, 6]
    static let guideOpacity: Double = 0.72
    static let verticalGuideTopGap: CGFloat = 7
    static let verticalGuideLineWidth: CGFloat = 1
    static let verticalGuideDash: [CGFloat] = [6, 8]
    static let verticalGuideOpacity: Double = 0.16
    static let compactTopInset: CGFloat = 106
    static let regularTopInset: CGFloat = 112
    static let compactTopInsetWithoutHighlight: CGFloat = 28
    static let regularTopInsetWithoutHighlight: CGFloat = 34
    static let compactBottomInset: CGFloat = 62
    static let regularBottomInset: CGFloat = 76
    static let horizontalPlotInset: CGFloat = 0
    static let bottomLabelMinWidth: CGFloat = 32
    static let bottomLabelMaxWidth: CGFloat = 56
    static let bottomLabelCompactFontSize: CGFloat = 13
    static let bottomLabelRegularFontSize: CGFloat = 15
    static let bottomLabelCompactWidthThreshold: CGFloat = 360
    static let bottomLabelYOffset: CGFloat = 40
    static let bottomLabelSpacing: CGFloat = 11
    static let bottomLabelTextOpacity: Double = 0.82
    static let bottomLabelMinimumScale: CGFloat = 0.75
    static let bottomLabelSwatchSize: CGFloat = 9
    static let bottomLabelSwatchShadowOpacity: Double = 0.75
    static let bottomLabelSwatchShadowRadius: CGFloat = 6
    static let trendBadgeWidth: CGFloat = 120
    static let trendBadgeCornerRadius: CGFloat = 17
    static let trendBadgeHorizontalPadding: CGFloat = 14
    static let trendBadgeVerticalPadding: CGFloat = 12
    static let trendBadgeIconSize: CGFloat = 16
    static let trendBadgeValueSize: CGFloat = 18
    static let trendBadgeValueMinimumScale: CGFloat = 0.78
    static let trendBadgeCaptionSize: CGFloat = 12
    static let trendBadgeSpacing: CGFloat = 5
    static let trendBadgeValueSpacing: CGFloat = 6
    static let trendBadgeBackgroundOpacity: Double = 0.80
    static let trendBadgeBorderOpacity: Double = 1
    static let trendBadgeBorderLineWidth: CGFloat = 1
    static let borderGlowLineWidthDelta: CGFloat = 1
    static let borderGlowOpacity: Double = 0.82
    static let borderGlowStartOpacity: Double = 0.55
    static let borderGlowEndOpacity: Double = 0.24
}
